export const listData = {
  totalCount: 7,
  list: [
    {
      id: 1,
      title: 'hello',
      user: { username: 'test' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
    {
      id: 2,
      title: 'test',
      user: { username: 'test' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
    {
      id: 3,
      title: 'ok',
      user: { username: 'test1' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
    {
      id: 4,
      title: 'redux',
      user: { username: 'test2' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
    {
      id: 5,
      title: 'redux',
      user: { username: 'test2' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
    {
      id: 6,
      title: 'redux',
      user: { username: 'test2' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
    {
      id: 7,
      title: 'redux',
      user: { username: 'test2' },
      publishDate: Date.now(),
      tags: ['sss', 'ss'],
      body: 'Hello This is page first Page!!',
    },
  ],
};
